---
- name: 'Configure Web App'
  hosts: localhost

  tasks:
    - name: make docker
      docker_container:
        image: busybox
        command: sleep 1d
        name: "busy{{ item }}"
      with_sequence: count=3

    - name: add hosts
      add_host:
        name: "busy{{ item }}"
        ansible_connection: docker
      with_sequence: count=3

- name: hi from docker
  hosts: dockers
  gather_facts: False

  tasks:
    - name: ping
      raw: echo $HOSTNAME


