---
- name: 'Demo Play'
  hosts: groupA

  tasks:
    - name: demo task 1
      debug:
        msg: "This is task 1"

    - name: demo task 2
      fail:
        msg: "This is task 2"
      when:
        - inventory_hostname == "host2"

- name: 'Demo Play'
  hosts: groupB

  tasks:
    - name: demo task 3
      debug:
        msg: "This is task 3"

    - name: demo task 4
      debug:
        msg: "This is task 4"